### ISSUE TITLE
Not working on Waterfox with Violentmonkey

### ISSUE THREAD

**Issue by hubblec4** [3F/GhrMeter.user.js#4]
There are no counter values with Waterfox.

**Comment by 3F** [comment]
I've just checked Waterfox 56.2.10 the latest release from official site. And I don't see any problems at least for manual injection from our [latest release](https://github.com/3F/GhrMeter.user.js/releases/latest):

![VirtualBoxVM_Dev_Win10x64_Waterfox](https://user-images.githubusercontent.com/3246589/59227622-76953000-8bde-11e9-8e88-499e6fc51b54.png)

probably a bug because of Violentmonkey

**Comment by 3F** [comment]
hmm, found this https://violentmonkey.github.io/2018/11/23/inject-into-context/

@hubblec4 Try `Mode: auto`. Works for me.
btw, I have no `Mode: content` with installed v2.10.5

**Comment by hubblec4** [comment]
Thanks for this hint. GhrMeter works fine. Many thanks.
